services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  frontend:
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - ./frontend:/usr/share/nginx/html
